age = input("how old are you?:")
if age == 12 :print("you are same age as me :/")
elif age <= 10 :print("you are younger than me =>")
elif age >= 13 :print("you are odler than me :<")
elif age >= 40 :print("sorry but you are old :<")